### ISSUE TITLE
Fails to create Zip when output file is a path

### ISSUE THREAD

**Issue by dweinstein** [nowsecure/node-applesign#88]
try running w/ parameter `--output ./some/relative/path/file.ipa`

**Comment by dweinstein** [comment]
related to https://github.com/nowsecure/node-applesign/issues/87

**Comment by trufae** [comment]
can't reproduce

**Comment by trufae** [comment]
ok i can reproduce now, the relative path issue only happens if you use applesign from $PATH, i always run it from the source directory.

The other issue is that it fails with the same error (exit 0 + exception) when passing a path that the user don't have permissions, but this is #87 . working on a fix now
